#cloud-config
write_files:
  - path: /config/custom-config.sh
    permissions: 0755
    owner: root:root
    content: |
      #!/bin/bash

      # Setup environmental variables
      TEMPADMINPWD=Ch4ngeMeImmediately!
      FN=f5-declarative-onboarding-1.9.0-1.noarch.rpm
      RPMURL=https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.9.0/f5-declarative-onboarding-1.9.0-1.noarch.rpm
      FILEPATH=/var/config/rest/downloads/
      CREDS=admin:$TEMPADMINPWD
      IP=127.0.0.1

      # Wait for MCPD to be up before running tmsh commands
      source /usr/lib/bigstart/bigip-ready-functions
      wait_bigip_ready 

      # Set temp admin password and disable hostname discovery via dhcp
      /bin/tmsh modify auth user admin password $TEMPADMINPWD
      /bin/tmsh modify sys management-dhcp sys-mgmt-dhcp-config request-options delete { host-name domain-name }
      /bin/tmsh save /sys config

      # Download declarative onboarding RPM from GitHub
      /bin/curl --silent --retry 20 --location --create-dirs --output $FILEPATH/$FN $RPMURL

      # Install declarative onboarding RPM
      LEN=$(/bin/wc -c $FILEPATH/$FN | /bin/cut -f 1 -d ' ')
      /bin/curl -kvu $CREDS https://$IP/mgmt/shared/file-transfer/uploads/$FN -H 'Content-Type: application/octet-stream' -H "Content-Range: 0-$((LEN - 1))/$LEN" -H "Content-Length: $LEN" -H 'Connection: keep-alive' --data-binary @$FILEPATH/$FN
      DATA="{\"operation\":\"INSTALL\",\"packageFilePath\":\"/var/config/rest/downloads/$FN\"}"
      /bin/curl -kvu $CREDS "https://$IP/mgmt/shared/iapp/package-management-tasks" -H "Origin: https://$IP" -H 'Content-Type: application/json;charset=UTF-8' --data $DATA

      # cloud-init completed
      TIMESTAMP=$(date)
      /bin/echo "cloud-init completed at $TIMESTAMP" > /config/cloud-init.finshed

runcmd:
  # NOTE: Commands must be non-blocking so send long running commands (polling/waiting for mcpd) to the background
  # NOTE: runcmd only runs at first boot
  - /config/custom-config.sh &